# Generated by Django 3.1.7 on 2021-03-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
